### ISSUE TITLE
@BeforeInsert doesn't work

### ISSUE THREAD

**Issue by simiong** [kibae/typeorm-auditing#3]
Thanks for developing this, it's exactly the lightweight library I've been looking for.
However, using the @BeforeInsert decorator doesn't seem to work.

This is the Audit Entity definition that I'm trying to use:
```
@AuditingEntity(User)
export class ZAuditUser extends User implements AuditingEntityDefaultColumns {

  @BeforeInsert()
  storeModifiedBy() {
    this._modifiedBy = this.userId;
  }

  readonly _seq: number;
  readonly _action: AuditingAction;
  readonly _modifiedAt: Date;

  @Column({ nullable: true, type: 'int' })
  _modifiedBy!: number;
}
```
The storeModifiedBy method doesn't seem to ever be called.

**Comment by kibae** [comment]
Hello, @simiong 
I fixed this bug, I just released version 0.5.0 to npm. Please reinstall the package and let me know if you have any other issues.
Thanks for reporting the bug. 🙇🏻

**Comment by kibae** [comment]
Hi @simiong, I think I missed an important part. I just released a new version 0.5.1. Could you please check it again?

**Comment by simiong** [comment]
Hey, @kibae, the fix worked perfectly. Thanks for helping out.
I'll let you know if I find any other issues.

**Comment by kibae** [comment]
@simiong I'm glad it was helpful.
Your comments and help are always welcome 👍
