### ISSUE TITLE
BeforeUpdate, BeforeRemove and BeforeSoftRemove don't working

### ISSUE THREAD

**Issue by roberto-souza** [kibae/typeorm-auditing#6]
Hello,

The subscribers @BeforeUpdate, @BeforeRemove and @BeforeSoftRemove don't get called when I use `dataSource.getRepository(Entity).remove(entity)`.

```ts
  @BeforeRemove()
  storeUserIdBeforeRemove(): void {
    if (this.userId) this._userId = this.userId;
  }
```
For example, when I use the code above, _userId is undefined.

Can you help me?

**Comment by kibae** [comment]
Hi @roberto-souza,

This could be a typeorm problem. Is the entity an instance of Entity?
```
// subscribers will not work
const entity = {...};
dataSource.getRepository(Entity).remove(entity);
```

```
// subscribers will work
const entity = new Entity(); // or if Entity is subclass of BaseEntity, you can use Entity.create(...) 
dataSource.getRepository(Entity).remove(entity);
```

**Comment by kibae** [comment]
https://github.com/typeorm/typeorm/issues/2577

Please refer to this link. 🙏

**Comment by kibae** [comment]
Please let me know if you have any related issues. 🙏
